#!/bin/bash -eu

declare -r DH_VERBOSE=

function create_log_dir {
    mkdir -p /var/log/cloudflare-dynamic-ip
    chmod 777 /var/log/cloudflare-dynamic-ip -R
    chown www-data:www-data /var/log/cloudflare-dynamic-ip


    mkdir -p /opt/cloudflare-dynamic-ip/storage
    chmod 777 /opt/cloudflare-dynamic-ip/storage -R
    chown www-data:www-data /opt/cloudflare-dynamic-ip/storage
}


case "$1" in
  configure)
      create_log_dir
  ;;

  abort-upgrade|abort-remove|abort-deconfigure)
    echo "postinst not doing anything for \`$1'" >&2
  ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
  ;;
esac

#DEBHELPER#
